name: Gulp Build

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing dependencies
        run: yarn
        
      - name: Building project
        run: gulp build
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Added Known Hosts
        run: ssh-keyscan -${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy on server with Rsync
        run: rsync -az -e "ssh -p ${{ secrets.SSH_PORT }}" --delete --exclude=.git ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DEST }}
