name: Guild Build

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing dependencies
        run: yarn
      - name: Building project
        run: gulp build
